version: '3'
services:
  data_upload_app:
    build: ./data_upload_app
    ports:
      - "7000:7000"
    networks:
      - vizzuality
  search-api:
    build: ./search-api
    ports:
      - "6200:6200"
    networks:
      - vizzuality
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - vizzuality

networks:
  vizzuality:
